[package]
name = "blackferrari2/props"
version = "0.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "INSTANCING!!!"

exclude = [
    "aftman.toml", 
    "README.md",
    "test.project.json"
]

[dependencies]
